package com.capgemini.MovieBookingSystem.entities;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.capgemini.MovieBookingSystem.beans.ShortCustomer;
@DynamoDBTable(tableName = "Booking")
public class Booking {
	private String bookingId;
	private ShortCustomer customer;
	private String theaterDetails;
	private String dateOfShow;
	private String showTiming;
	private String screenName;
	private String movieName;
	private double amount;
	private List<String> bookedSeats;
	private Transaction transaction;
	private SeatPlan seatPlan;
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getBookingId() {
		return bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}
	@DynamoDBAttribute
	public ShortCustomer getCustomer() {
		return customer;
	}

	public void setCustomer(ShortCustomer customer) {
		this.customer = customer;
	}

	@DynamoDBAttribute
	public String getTheaterDetails() {
		return theaterDetails;
	}

	public void setTheaterDetails(String theaterDetails) {
		this.theaterDetails = theaterDetails;
	}
	@DynamoDBAttribute
	public String getDateOfShow() {
		return dateOfShow;
	}

	public void setDateOfShow(String dateOfShow) {
		this.dateOfShow = dateOfShow;
	}
	@DynamoDBAttribute
	public String getShowTiming() {
		return showTiming;
	}

	public void setShowTiming(String showTiming) {
		this.showTiming = showTiming;
	}
	@DynamoDBAttribute
	public String getScreenName() {
		return screenName;
	}

	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}
	@DynamoDBAttribute
	public String getMovieName() {
		return movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}
	@DynamoDBAttribute
	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}
	@DynamoDBAttribute
	public List<String> getBookedSeats() {
		return bookedSeats;
	}

	public void setBookedSeats(List<String> bookedSeats) {
		this.bookedSeats = bookedSeats;
	}
	@DynamoDBAttribute
	public Transaction getTransaction() {
		return transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}
	@DynamoDBAttribute
	public SeatPlan getSeatPlan() {
		return seatPlan;
	}

	public void setSeatPlan(SeatPlan seatPlan) {
		this.seatPlan = seatPlan;
	}

}
