package com.capgemini.MovieBookingSystem.entities;

import java.time.LocalDate;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.capgemini.MovieBookingSystem.beans.ScreenTime;
@DynamoDBTable(tableName = "Screen")
public class Screen {
	private String theaterId;
	private String screenId;
	private String screenName;
	private String movieDimension;
	private LocalDate dateOfTheShow;
	private List<ScreenTime> screenTimes;
	
	@DynamoDBHashKey
	public String getTheaterId() {
		return theaterId;
	}
	public void setTheaterId(String theaterId) {
		this.theaterId = theaterId;
	}
	@DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
	public String getScreenId() {
		return screenId;
	}
	
	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}
	@DynamoDBAttribute
	public String getScreenName() {
		return screenName;
	}
	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}
	@DynamoDBAttribute
	public String getMovieDimension() {
		return movieDimension;
	}
	public void setMovieDimension(String movieDimension) {
		this.movieDimension = movieDimension;
	}
	@DynamoDBAttribute
	public LocalDate getDateOfTheShow() {
		return dateOfTheShow;
	}
	public void setDateOfTheShow(LocalDate dateOfTheShow) {
		this.dateOfTheShow = dateOfTheShow;
	}
	@DynamoDBAttribute
	public List<ScreenTime> getScreenTimes() {
		return screenTimes;
	}
	public void setScreenTimes(List<ScreenTime> screenTimes) {
		this.screenTimes = screenTimes;
	}
	
	

}
