package com.capgemini.MovieBookingSystem.entities;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName = "SeatPlan")
public class SeatPlan {
	private String seatPlanId;
	private List<String> bookedSeats;
	private List<String> LockedSeats;
	
	public SeatPlan() {
	}
	
	public SeatPlan(String seatPlanId, List<String> bookedSeats, List<String> lockedSeats) {
		super();
		this.seatPlanId = seatPlanId;
		this.bookedSeats = bookedSeats;
		LockedSeats = lockedSeats;
	}
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getSeatPlanId() {
		return seatPlanId;
	}
	public void setSeatPlanId(String seatPlanId) {
		this.seatPlanId = seatPlanId;
	}
	@DynamoDBAttribute
	public List<String> getBookedSeats() {
		return bookedSeats;
	}
	public void setBookedSeats(List<String> bookedSeats) {
		this.bookedSeats = bookedSeats;
	}
	@DynamoDBAttribute
	public List<String> getLockedSeats() {
		return LockedSeats;
	}
	public void setLockedSeats(List<String> lockedSeats) {
		LockedSeats = lockedSeats;
	}
	
	
}
