package com.capgemini.MovieBookingSystem.entities;

import java.util.List;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.capgemini.MovieBookingSystem.beans.Address;
import com.capgemini.MovieBookingSystem.beans.Seat;
import com.capgemini.MovieBookingSystem.beans.ShortCity;
import com.capgemini.MovieBookingSystem.beans.ShortMovie;
import com.capgemini.MovieBookingSystem.beans.ShortScreen;

@DynamoDBTable(tableName = "Theaters")
public class Theater {
	
	private	String theatreId;
	private	String theatreName;
	private	Address address;
	private	ShortCity city;
	private	List<ShortScreen> screens;
	private	List<ShortMovie> movies;
	private Integer rows;
	private Integer columns;
	private Map<Seat,Integer> noOfSeatsPerType;

	public Theater() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Theater(String theatreId, String theatreName, Address address, ShortCity city, List<ShortScreen> screens,
			List<ShortMovie> movies, Integer rows, Integer columns, Map<Seat, Integer> noOfSeatsPerType) {
		super();
		this.theatreId = theatreId;
		this.theatreName = theatreName;
		this.address = address;
		this.city = city;
		this.screens = screens;
		this.movies = movies;
		this.rows = rows;
		this.columns = columns;
		this.noOfSeatsPerType = noOfSeatsPerType;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getTheatreId() {
		return theatreId;
	}

	public void setTheatreId(String theatreId) {
		this.theatreId = theatreId;
	}

	@DynamoDBAttribute
	public String getTheatreName() {
		return theatreName;
	}

	public void setTheatreName(String theatreName) {
		this.theatreName = theatreName;
	}

	@DynamoDBAttribute
	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@DynamoDBAttribute
	public ShortCity getCity() {
		return city;
	}

	public void setCity(ShortCity city) {
		this.city = city;
	}

	@DynamoDBAttribute
	public List<ShortScreen> getScreens() {
		return screens;
	}

	public void setScreens(List<ShortScreen> screens) {
		this.screens = screens;
	}

	@DynamoDBAttribute
	public List<ShortMovie> getMovies() {
		return movies;
	}

	public void setMovies(List<ShortMovie> movies) {
		this.movies = movies;
	}

	@DynamoDBAttribute
	public Integer getRows() {
		return rows;
	}

	public void setRows(Integer rows) {
		this.rows = rows;
	}

	@DynamoDBAttribute
	public Integer getColumns() {
		return columns;
	}

	public void setColumns(Integer columns) {
		this.columns = columns;
	}
	@DynamoDBAttribute
	public Map<Seat,Integer> getNoOfSeatsPerType() {
		return noOfSeatsPerType;
	}

	public void setNoOfSeatsPerType(Map<Seat,Integer> noOfSeatsPerType) {
		this.noOfSeatsPerType = noOfSeatsPerType;
	}
	
}
