package com.capgemini.MovieBookingSystem.entities;

import java.time.Instant;
import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.capgemini.MovieBookingSystem.beans.Address;
import com.capgemini.MovieBookingSystem.beans.CardDetails;
import com.capgemini.MovieBookingSystem.beans.ShortBooking;
import com.capgemini.MovieBookingSystem.enums.Role;
import com.capgemini.MovieBookingSystem.enums.RoleConverter;

@DynamoDBTable(tableName = "User")
public class User {
	private String userId;
	private String firstName;
	private String lastName;
	private Date DOB;
	private String phone;
	private String email;
	private String password;
	private String imgPath;
	private List<ShortBooking> bookings;
	private List<Address> favoritePlaces;
	private List<CardDetails> savedCards;
	private Role role;
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	@DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	@DynamoDBAttribute
	public Date getDOB() {
		return DOB;
	}

	public void setDOB(Date dOB) {
		DOB=Date.from(Instant.now());
//		DOB = dOB;
	}
	@DynamoDBAttribute
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@DynamoDBAttribute
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@DynamoDBAttribute
	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}
	@DynamoDBAttribute
	public List<ShortBooking> getBookings() {
		return bookings;
	}

	public void setBookings(List<ShortBooking> bookings) {
		this.bookings = bookings;
	}
	@DynamoDBAttribute
	public List<Address> getFavoritePlaces() {
		return favoritePlaces;
	}

	public void setFavoritePlaces(List<Address> favoritePlaces) {
		this.favoritePlaces = favoritePlaces;
	}
	@DynamoDBAttribute
	public List<CardDetails> getSavedCards() {
		return savedCards;
	}

	public void setSavedCards(List<CardDetails> savedCards) {
		this.savedCards = savedCards;
	}
	@DynamoDBTypeConverted(converter = RoleConverter.class)
	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}
}
